# Generated by Django 4.2.7 on 2025-12-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.driverdetail'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.locationdetail'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='tanker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.tankerdetail'),
        ),
    ]
