# Generated by Django 5.1.7 on 2025-04-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.locationdetail'),
        ),
    ]
