# Generated by Django 5.1.7 on 2025-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
