# Generated by Django 5.1.7 on 2025-04-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='EndLocation',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='StartLocation',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='rackingDetails',
        ),
    ]
