# Generated by Django 5.1.7 on 2025-04-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_rename_endlocation_orderdetail_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.locationdetail'),
        ),
    ]
