# Generated by Django 5.1.7 on 2025-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_userdetail_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='passwords',
            field=models.CharField(max_length=255),
        ),
    ]
