# Generated by Django 5.1.7 on 2025-04-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_userdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
    ]
