# Generated by Django 5.1.7 on 2025-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_remove_userdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='passwords',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
