# Generated by Django 5.1.7 on 2025-04-16 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_userdetail_passwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(default='deafultuser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='passwords',
            field=models.CharField(default='defaultpass', max_length=255),
        ),
    ]
