# Generated by Django 5.1.7 on 2025-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_userdetail_user_alter_userdetail_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='passwords',
            field=models.CharField(max_length=255),
        ),
    ]
