# Generated by Django 5.1.7 on 2025-06-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TankerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(choices=[(1000, '1000 liters'), (2000, '2000 liters'), (5000, '5000 liters'), (10000, '10000 liters')])),
                ('category', models.CharField(choices=[('DRINKING', 'Drinking Water'), ('NON_DRINKING', 'Non-Drinking Water'), ('BOTH', 'Drinking & Usage Water')], max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterTankerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_tanker_name', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('driving_license', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('registration_cert', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('vechicle_insurance', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('vechicle_permit', models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='Supplier.driveravailability')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.locationdetail')),
            ],
        ),
    ]
