# Generated by Django 5.1.7 on 2025-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankerdetail',
            name='category',
            field=models.CharField(choices=[('DRINKING', 'Drinking Water'), ('NON_DRINKING', 'Non-Drinking Water'), ('BOTH', 'Drinking & Usage Water')], max_length=50),
        ),
    ]
