# Generated by Django 5.1.7 on 2025-04-17 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed_orders', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.payment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.driverdetail')),
            ],
        ),
    ]
