# Generated by Django 4.2.7 on 2025-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertankerdocument',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
