# Generated by Django 5.1.7 on 2025-04-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_alter_tankerdetail_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankerdetail',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.driverdetail'),
        ),
    ]
