# Generated by Django 5.1.7 on 2025-04-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_alter_tankerdetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankerdetail',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.watertankerdocument'),
        ),
        migrations.AlterField(
            model_name='tankerdetail',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.driverdetail'),
        ),
    ]
