# Generated by Django 5.1.7 on 2025-04-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_alter_tankerdetail_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplieruser'),
        ),
    ]
