# Generated by Django 5.1.7 on 2025-04-16 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_userdetail_passwords'),
        ('Supplier', '0003_alter_tankerdetail_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankerdetail',
            name='document',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Supplier.watertankerdocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tankerdetail',
            name='driver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Supplier.driverdetail'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.orderdetail')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='Supplier.driverdetail')),
            ],
        ),
    ]
