# Generated by Django 5.1.7 on 2025-04-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
        ('Supplier', '0003_alter_driverdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.userdetail'),
        ),
    ]
