# Generated by Django 4.2.7 on 2025-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_watertankerdocument_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vechicle_insurance',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vechicle_permit',
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vehicle_insurance',
            field=models.FileField(blank=True, null=True, upload_to='tanker/insurance/'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vehicle_permit',
            field=models.FileField(blank=True, null=True, upload_to='tanker/permit/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='tanker/aadhar/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='tanker/license/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='is_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='tanker/pan/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tanker/profile/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='registration_cert',
            field=models.FileField(blank=True, null=True, upload_to='tanker/rc/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='water_tanker_name',
            field=models.CharField(max_length=100),
        ),
    ]
