# Generated by Django 5.1.7 on 2025-04-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_alter_driverdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.driveravailability'),
        ),
    ]
