# Generated by Django 5.1.7 on 2025-04-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_alter_tankerdetail_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earning',
        ),
    ]
