# Generated by Django 5.1.7 on 2025-04-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_initial'),
        ('Supplier', '0005_alter_driverdetail_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='Supplier.driveravailability'),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.userdetail'),
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
    ]
