# Generated by Django 5.1.7 on 2025-04-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_userdetail_passwords'),
        ('Supplier', '0005_delete_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vechicle_insurance',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vechicle_permit',
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='insurance_validity',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='license_number',
            field=models.CharField(default='DEFAULT123', max_length=20),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='pollution_certificate',
            field=models.CharField(default='POLL12345', max_length=50),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='registration_number',
            field=models.CharField(default='REG1234', max_length=20),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.userdetail'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vehicle_insurance',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vehicle_permit',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vehicle_type',
            field=models.CharField(default='vechivletype1234', max_length=255),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tanker_photos/'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='registration_cert',
            field=models.FileField(blank=True, null=True, upload_to='tanker_documents/'),
        ),
    ]
