# Generated by Django 5.1.7 on 2025-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0006_remove_watertankerdocument_vechicle_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='insurance_validity',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='pollution_certificate',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vehicle_insurance',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vehicle_permit',
        ),
        migrations.RemoveField(
            model_name='watertankerdocument',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vechicle_insurance',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AddField(
            model_name='watertankerdocument',
            name='vechicle_permit',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
        migrations.AlterField(
            model_name='watertankerdocument',
            name='registration_cert',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image.jpg'),
        ),
    ]
