# Generated by Django 5.1.7 on 2025-04-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0006_alter_driverdetail_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankerdetail',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supplier.watertankerdocument'),
        ),
    ]
